name: basic testing

on: [push, pull_request]

jobs:
    linux_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configuring CMake
              run: |
                  mkdir ./build
                  cd build
                  cmake ..
            
            - name: Building
              run: |
                  cd build
                  cmake --build .

            - name: Running sample
              run: |
                  cd build/bin
                  ./sample -s 10 -t 2

            - name: Running tests
              run: |
                  cd build
                  ctest --output-on-failure

    macos_test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Installing OpenMP
              run: |
                  brew install libomp

            - name: Configuring CMake
              run: |
                  mkdir ./build
                  cd build
                  export OpenMP_ROOT=$(brew --prefix)/opt/libomp
                  cmake ..
            
            - name: Building
              run: |
                  cd build
                  cmake --build .

            - name: Running sample
              run: |
                  cd build/bin
                  ./sample -s 10 -t 2

            - name: Running tests
              run: |
                  cd build
                  ctest --output-on-failure

    windows_test:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configuring CMake
              run: |
                  mkdir build
                  cd build
                  cmake ..
            
            - name: Building
              run: |
                  cd build
                  cmake --build .

            - name: Running sample
              run: |
                  cd build\bin
                  .\sample -s 10 -t 2

            - name: Running tests
              run: |
                  cd build
                  ctest -C Debug --output-on-failure

